### ISSUE TITLE
Some questions about another one redux tooling library.

### ISSUE THREAD

**Issue by amabunny** [Redux-Cool/redux-cool#12]
Hi! My name is Sergei, I'm 5 year experienced react developer and in my projects I used these libraries:

- redux
- redux-toolkit
- effector

And I found an explain of your motivation to create redux-cool in the documentation:

_ReduxToolkit tried to solve these problems but with no result. I think that the creators of ReduxToolkit did not know about the important problems that emerge when we start using Redux in big and complex projects._ 

Could you describe what you mean? What problems? Why it gives you no result? What important problems? Any examples of complex projects? Would you try to resolve some problems locally in your project?

In our projects with react-toolkit we creating feature directory with store folder containing files:
- feature.actions.ts
- feature.reducer.ts
- feature.types.ts
- feature.epics.ts
- feature.selectors.ts

Then we import each one in feature store api initializer:

```
import * as actions from './feature.actions.ts';
import * as selectors from './feature.selectors.ts';
import * as epics from './feature.epics.ts';
import { reducer } from './feature.reducer.ts';
export * from './feature.types.ts';

export const featureApi = {
  reducer,
  selectors,
  actions,
  epics,
}
```

And we got something like that:
![image](https://user-images.githubusercontent.com/25837050/116583799-29381e00-a930-11eb-880e-7c25bd11aded.png)

And what's about typescript? I don't see any information about typescript support. 
In any case you need to explain problems that you resolved, what you get and what you lost. Now it looks like you didn't understand how to cook apps with redux-toolkit, nothing personal. 

I really wish you can make something that will be better than redux-toolkit, but now it is not so.

Regards, Sergei.

**Comment by Ruben-Arushanyan** [comment]
Hi Sergey! My name is Ruben! Thanks for the question.

I wrote this library to solve these three main problems. [Problems](https://redux-cool.js.org/docs/introduction/problems)

And the typescript support will be in 2 day․
